### ISSUE TITLE
default_subcommand doesn't accept options and parameters from the subcommand

### ISSUE THREAD

**Issue by kvechera** [mdub/clamp#98]
Invoking a command via 'default_subcommand' mechanism results in error during processing the options or parameters of the subcommand.

Example:
```
   subcommand 'module', 'module management' do
      self.default_subcommand = 'list'
      subcommand 'list', 'list modules' do
        option '--role', 'role', 'module role'
        def execute
        ...
```

I.e. I define a subcommand 'module' with a nested subcommand 'list'. The 'list' is set as default subcommand. But if one invokes 'module' with an option 'name', he gets an 'Unrecognized option `--role`'

```
$ mm module list --role=admin
Ok

$ mm module --role=admin
ERROR: Unrecognised option '--role'

See: 'mm module --help'

```

Expected behavior - process the option '--role' both for 'mm module list' subcommands too.

Version: clamp 1.3.0

**Comment by mdub** [comment]
Sorry, but I can't see a good way to "fix" this. `default_subcommand` is meant as a shortcut when no command or options are provided.

I certainly don't think it's practical to accept positional parameters for a default subcommand, as it would be impossible to determine whether the argument was a subcommand or a parameter.

I guess one _could_ (in theory) default the subcommand if only options were provided. The trouble is, Clamp processes and consumes options _before_ looking for a subcommand, so that would require significant changes to the internals.

All I can suggest, in your case, is hoisting the `--role` option up to the `module` subcommand.  Then Clamp would recognise it, and it's value would still be available when `list` was executed.
